spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/yovendo
spring.datasource.username=root
spring.datasource.password=jeyson1171

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=Y292ZW5kb19zZWNyZXRfa2V5X3BhcmFfZWwtcHJveWVjdG8tMjU=
jwt.expiration=86400000